version: "3"
services:
  bundlesofamaze:
    image: __DockerImage__
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 500M
      restart_policy:
        condition: on-failure
